### ISSUE TITLE
cudaErrorNoKernelImageForDevice

### ISSUE THREAD

**Issue by Bradly-s** [xiteng01/CVPR2023_foundation_model_Track1#3]
May I ask how to solve it? The problem is  as follows:
————————————————————————————————————————————————————
sys.platform            linux
Python                  3.7.0 | packaged by conda-forge | (default, Nov 12 2018, 20:15:55) [GCC 7.3.0]
numpy                   1.21.6
detectron2              imported a wrong installation
detectron2._C           not built correctly: {e}
Compiler ($CXX)         c++ (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
CUDA compiler           Build cuda_11.1.TC455_06.29069683_0
DETECTRON2_ENV_MODULE   <not set>
PyTorch                 1.8.0+cu111 
PyTorch debug build     False
GPU available           Yes
GPU 0                   NVIDIA GeForce RTX 3080 (arch={cap})
Driver version          525.89.02
CUDA_HOME               /usr/local/cuda-11.1
Pillow                  9.4.0
torchvision             0.9.0+cu111 
torchvision arch flags  3.5, 5.0, 6.0, 7.0, 7.5, 8.0, 8.6
fvcore                  0.1.5.post20220119
iopath                  0.1.10
cv2                     4.4.0

PyTorch built with:
  - GCC 7.3
  - C++ Version: 201402
  - Intel(R) Math Kernel Library Version 2020.0.0 Product Build 20191122 for Intel(R) 64 architecture applications
  - Intel(R) MKL-DNN v1.7.0 (Git Hash 7aed236906b1f7a05c0917e5257a1af05e9ff683)
  - OpenMP 201511 (a.k.a. OpenMP 4.5)
  - NNPACK is enabled
  - CPU capability usage: AVX2
  - CUDA Runtime 11.1
  - NVCC architecture flags: -gencode;arch=compute_37,code=sm_37;-gencode;arch=compute_50,code=sm_50;-gencode;arch=compute_60,code=sm_60;-gencode;arch=compute_70,code=sm_70;-gencode;arch=compute_75,code=sm_75;-gencode;arch=compute_80,code=sm_80;-gencode;arch=compute_86,code=sm_86
  - CuDNN 8.0.5
  - Magma 2.5.2
  - Build settings: BLAS_INFO=mkl, BUILD_TYPE=Release, CUDA_VERSION=11.1, CUDNN_VERSION=8.0.5, CXX_COMPILER=/opt/rh/devtoolset-7/root/usr/bin/c++, CXX_FLAGS= -Wno-deprecated -fvisibility-inlines-hidden -DUSE_PTHREADPOOL -fopenmp -DNDEBUG -DUSE_KINETO -DUSE_FBGEMM -DUSE_QNNPACK -DUSE_PYTORCH_QNNPACK -DUSE_XNNPACK -O2 -fPIC -Wno-narrowing -Wall -Wextra -Werror=return-type -Wno-missing-field-initializers -Wno-type-limits -Wno-array-bounds -Wno-unknown-pragmas -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wno-unused-function -Wno-unused-result -Wno-unused-local-typedefs -Wno-strict-overflow -Wno-strict-aliasing -Wno-error=deprecated-declarations -Wno-stringop-overflow -Wno-psabi -Wno-error=pedantic -Wno-error=redundant-decls -Wno-error=old-style-cast -fdiagnostics-color=always -faligned-new -Wno-unused-but-set-variable -Wno-maybe-uninitialized -fno-math-errno -fno-trapping-math -Werror=format -Wno-stringop-overflow, LAPACK_INFO=mkl, PERF_WITH_AVX=1, PERF_WITH_AVX2=1, PERF_WITH_AVX512=1, TORCH_VERSION=1.8.0, USE_CUDA=ON, USE_CUDNN=ON, USE_EXCEPTION_PTR=1, USE_GFLAGS=OFF, USE_GLOG=OFF, USE_MKL=ON, USE_MKLDNN=ON, USE_MPI=OFF, USE_NCCL=ON, USE_NNPACK=ON, USE_OPENMP=ON, 
W0404 20:15:07.214385  8363 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 10.2
W0404 20:15:07.215968  8363 gpu_resources.cc:91] device: 0, cuDNN Version: 8.7.
ERROR - outputs/vitbase_joint_training - Failed after 0:00:01!
Traceback (most recent call last):
  File "tools/ufo_train.py", line 231, in <module>
    main(args)
  File "tools/ufo_train.py", line 223, in main
    ex.run(config_updates={'args': args, 'cfg_for_sacred': LazyConfig.to_dict(cfg)})
  File "site-packages/sacred/experiment.py", line 276, in run
    run()
  File "site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "tools/ufo_train.py", line 219, in do_train_sacred
    do_train(args, cfg, cfg_for_sacred, _run)
  File "tools/ufo_train.py", line 110, in do_train
    model = instantiate(cfg.model)
  File "./detectron2/config/instantiate.py", line 62, in instantiate
    cfg = {k: instantiate(v) for k, v in cfg.items()}
  File "./detectron2/config/instantiate.py", line 62, in <dictcomp>
    cfg = {k: instantiate(v) for k, v in cfg.items()}
  File "./detectron2/config/instantiate.py", line 78, in instantiate
    return cls(**cfg)
  File "./modeling/backbones/vit.py", line 513, in __init__
    self.apply(self._init_weights)
  File ".../site-packages/paddle/fluid/dygraph/layers.py", line 245, in apply
    layer.apply(fn)
  File ".../site-packages/paddle/fluid/dygraph/layers.py", line 245, in apply
    layer.apply(fn)
  File ".../python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 245, in apply
    layer.apply(fn)
  File ".../python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 247, in apply
    fn(self)
  File "./modeling/backbones/vit.py", line 528, in _init_weights
    trunc_normal_(m.weight)
  File "lib/python3.7/site-packages/paddle/fluid/initializer.py", line 474, in __call__
    'std', self._std_dev, 'seed', self._seed)
SystemError: (Fatal) Operator truncated_gaussian_random raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at /paddle/paddle/fluid/imperative/tracer.cc:307)

**Comment by yyyyyyfs** [comment]
Possibel issue with incorrect CUDA version。
From paddlepaddle official document，paddlepaddle-gpu==2.3.2 can correspond CUDA 11.2 version

**Comment by Bradly-s** [comment]
ok，thank you very much
